config/routes.rb
Users::Application.routes.draw do
  root 'welcome#index'
  resources :users
  get "sign_up",  to: 'users#new', via: 'get'
  get 'home'   ,  to: 'welcome#index'  , via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  	before_save { self.email = email.downcase }
  	validates :name,  presence: true, length: { maximum: 50 }
  	validates :email, presence: true
  	has_secure_password
  	validates :password, length: { minimum: 6 }
   
    def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end
	def show
		@user = User.find(params[:id])
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = 'Welcome to the User list'
			redirect_to @user
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password,
		 :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
        <div class="container">
          <%= link_to "page of users", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Show all", users_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>.












    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Users</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
    <div class="container">

    <%= yield %>

    </div>

</body>
</html>

app/views/users/index.html.erb
<h1>List of User </h1>
 <ul>
    <% @user.each do |user| %>
      <li><%= user.name %> <%= link_to "Admin", '#' %> <%= link_to "User", '#' %></li>
    <% end %>
  </ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset4">
    <%= form_for (@user) do |f| %>
      <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
     <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
  </div>
  <% end %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %><br/>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
<aside class="span4">
	<section>
	<br>
		<h2>
		<%= @user.name %>
		</h2>
	</section>
</aside>
</div>

app/views/welcome/index.html.erb
<h1>Hello to Users Page</h1>